### ISSUE TITLE
CMU season datset images

### ISSUE THREAD

**Issue by weiyunchen92** [maunzzz/fine-grained-segmentation-networks#3]
hello Mans,
I am trying to download the images of CMU datset based on the .sh file as you mentioned in Cross-Season dataset https://www.dropbox.com/sh/n4gt3eazydg8ny0/AAAthUiwz_kYGheSFJCsprtHa?dl=0.
But the website for the dataset http://3dvis.ri.cmu.edu/data-sets/localization/ is not longer available and we can just download the similar one from https://www.visuallocalization.net/datasets/. But the data folder is organised in different ways. Is it possible for you to upload the CMU dataset you used for training? Thanks.

**Comment by maunzzz** [comment]
Hi,
I'm still hoping that they will start hosting the dataset again.
Anyway, you can use this link for now:
https://www.dropbox.com/sh/thm0dq393p1q42y/AACWblVPGR8gPlLlN-jBBwlya?dl=0

Den ons 20 nov. 2019 kl 15:47 skrev weiyunchen92 <notifications@github.com>:

**Comment by weiyunchen92** [comment]
@maunzzz thank you so much

**Comment by chenusc11** [comment]
Hi, unfortunately, the above mentioned link does not seem to work anymore. Could you please share a new link again? Great thanks!
