### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by weiyunchen92** [maunzzz/fine-grained-segmentation-networks#4]
Hi,
you have mentioned in you paper, that you integrate your segmentation result into this semantic visual localization algorithum (http://openaccess.thecvf.com/content_ECCV_2018/papers/Carl_Toft_Semantic_Match_Consistency_ECCV_2018_paper.pdf ) and use it to evaluation your performance as well. But I couldn't find the release code based on this localization method. Do you reproduct this paper on your own? And Is it possible for you to release the code for evaluation as well? Thank you in advance.

**Comment by maunzzz** [comment]
Hi!
I'm afraid I do not have an implementation of the localization methods. Carl Toft is a colleague of mine (and co-author of the FGSN-paper), so he did the localization experiments. I'll ask him if he is planning on releasing a public version of the code.

**Comment by weiyunchen92** [comment]
> Hi!
> I'm afraid I do not have an implementation of the localization methods. Carl Toft is a colleague of mine (and co-author of the FGSN-paper), so he did the localization experiments. I'll ask him if he is planning on releasing a public version of the code.

**Comment by weiyunchen92** [comment]
@maunzzz Thank you for your reply. If your college Carl Toft can release the public version, it would be really helpful.
