### ISSUE TITLE
Evaluating on my own data

### ISSUE THREAD

**Issue by kxhit** [maunzzz/fine-grained-segmentation-networks#5]
Hi! Thanks for sharing your work!
I'd like to know which model should be used to evaluate my own data. I modified `cluster_images_in_folder.py` and loaded `rc-100clusters.pth` for a try, but the output images are all black. Is there something wrong? Did I miss anything?
Thanks a lot!

**Comment by maunzzz** [comment]
Hi!
Probably not, I believe the images are saved without any colormap so they might look just black in an image viewer.
You can try loading them and look at the values.

**Comment by kxhit** [comment]
Hi! @maunzzz Thanks for your reply.
I print the value of saved images and got all zeros. 
Should I notice something when using `segmentor.run_and_save()`? Could you give me an example `.py` of inferencing one image?
 I haven't got a clue what to do.  Thanks a lot!

**Comment by maunzzz** [comment]
Hi, sorry for the late reply. Hopefully you solved your issue by now.
If you haven't, I would suggest looking at the Segmentor class in utils/segmentor.py
The run_and_save accepts a path to an image so it should be straightforward to do inference on one image.
